### ISSUE TITLE
Running tests with jest hangs

### ISSUE THREAD

**Issue by jozsi** [hfour/wsrun#32]
Hello,

I am trying to run my tests (using jest), but it hangs:
1. normal run
```
➜  ~/Dev/frontend (dev) yarn wsrun test
yarn run v1.9.4
$ /Users/jozsi/Dev/frontend/node_modules/.bin/wsrun test
project5
$ react-app-rewired test --env=jsdom
project6
$ echo 'No tests here yet'
 | No tests here yet
project4
$ react-app-rewired test --env=jsdom
project3
$ react-app-rewired test --env=jsdom
project2
$ react-app-rewired test --env=jsdom
project1
$ react-app-rewired test --env=jsdom
project5
 | No tests found related to files changed since last commit.
 | 
project4
 | No tests found related to files changed since last commit.
project3
 | No tests found related to files changed since last commit.
project4
 | 
project3
 | 
project2
 | No tests found related to files changed since last commit.
project1
 | No tests found related to files changed since last commit.
project2
 | 
project1
 | 
^CStopping 6 active children
```

2. using `--serial`
```
➜  ~/Dev/frontend (dev) yarn wsrun test --serial
yarn run v1.9.4
$ /Users/jozsi/Dev/frontend/node_modules/.bin/wsrun test --serial
project5
$ react-app-rewired test --env=jsdom
 | No tests found related to files changed since last commit.
 | 
^CStopping 2 active children
/Users/jozsi/Dev/frontend/node_modules/wsrun/build/parallelshell.js:161
                ch.cp.removeAllListeners('close');
                      ^

TypeError: Cannot read property 'removeAllListeners' of undefined
    at children.forEach.ch (/Users/jozsi/Dev/frontend/node_modules/wsrun/build/parallelshell.js:161:23)
    at Array.forEach (<anonymous>)
    at RunGraph.closeAll (/Users/jozsi/Dev/frontend/node_modules/wsrun/build/parallelshell.js:160:27)
    at process.emit (events.js:182:13)
```

**Comment by spion** [comment]
If possible, you should probably use jest's projects setting - its far more efficient.

In the workspace dir package.json:

```json
{
  "jest": {
    "projects": [
      "<rootDir>/packages/p1",
      "<rootDir>/packages/p2",
      ...
    }
  }
}
```

**Comment by spion** [comment]
We made quite a few changes since the issue was originally opened, but please let us know if it still persists.

**Comment by PaulRBerg** [comment]
Still hangs when using it inside a lerna monorepo with wsrun 3.6.4 and jest 23.6.0.

**Comment by Pranit-Harekar** [comment]
This issue persists in yarn workspaces with jest framework. @spion let me know if you want me to open a new issue.

**Comment by spion** [comment]
I can reopen this one. it would be helpful if there was a test case that reproduces it though.

**Comment by spion** [comment]
This needs more info, preferably a small reproduction case. Will close again
