### ISSUE TITLE
ca in nmprc -> TypeError: Cannot create property '' on string

### ISSUE THREAD

**Issue by tao-cumplido** [hfour/wsrun#85]
I have a private registry and had up till now used the `ca` field for the certificate in the .npmrc.

Running a script with yarn in each package wasn't a problem but trying to run the scripts in parallel with wsrun resulted in the following error:

```
TypeError: Cannot create property '' on string '"-----BEGIN CERTIFICATE-----\n...-----END CERTIFICATE-----"'
```

I moved the certificate to its own file and used `cafile` instead of `ca` in .npmrc and now it works.

**Comment by spion** [comment]
Do you have the rest of the stack trace preferably with line numbers included?

**Comment by tao-cumplido** [comment]
this should be the relevant info from the yarn-error.log

```sh
Yarn version: 
  1.21.0

Node version: 
  12.13.0

Platform: 
  win32 x64

Trace: 
  TypeError: Cannot create property '' on string '-----BEGIN CERTIFICATE-----\n...-----END CERTIFICATE-----'
      at set (C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:53902:28)
      at set (C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:53906:14)
      at set (C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:53886:16)
      at Function.objectPath.set (C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:53939:14)
      at NpmRegistry.mergeEnv (C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:96009:18)
      at NpmRegistry.<anonymous> (C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:31899:12)
      at Generator.next (<anonymous>)
      at step (C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:304:30)
      at C:\Users\taocu\AppData\Roaming\nvm\v12.13.0\node_modules\yarn\lib\cli.js:322:14
      at new Promise (<anonymous>)
```

**Comment by spion** [comment]
Seems to be a crash type error in `yarn`, not wsrun
